# Generated by Django 3.2.4 on 2023-06-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panelbuilding', '0002_initial'),
        ('prescreener', '0002_auto_20230531_1145'),
        ('panelengagement', '0001_initial'),
        ('comman', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemaskinglogic',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='pagemaskinglogic',
            name='pe_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelengagement.pecampaign'),
        ),
        migrations.AddField(
            model_name='pagemaskinglogic',
            name='prescreener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.prescreener'),
        ),
        migrations.AddField(
            model_name='pagepipinglogic',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='pagepipinglogic',
            name='pe_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelengagement.pecampaign'),
        ),
        migrations.AddField(
            model_name='pagepipinglogic',
            name='prescreener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.prescreener'),
        ),
    ]
