# Generated by Django 3.2.4 on 2023-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230524_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='is_for_project',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
