# Generated by Django 3.2.4 on 2023-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_supplier_is_for_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='iesamplingstatus',
            name='county_mismath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
