# Generated by Django 3.2.4 on 2023-06-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreener', '0002_auto_20230531_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_external_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='pe_campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='prescreener_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
