# Generated by Django 3.2.4 on 2023-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreener', '0003_auto_20230613_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_external_sample',
        ),
        migrations.AddField(
            model_name='externalsamplepanelistanswer',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsamplepanelistanswer',
            name='pe_campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsamplepanelistanswer',
            name='prescreener_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
