# Generated by Django 3.2.4 on 2023-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreener', '0004_auto_20230613_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicateorfraudpanelistid',
            name='county_mismath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
