# Generated by Django 3.2.4 on 2023-05-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescreener', '0001_initial'),
        ('panelengagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurveyRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelengagement.redemption')),
                ('user_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.usersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='UserSurveyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(blank=True, null=True)),
                ('points_spent', models.IntegerField(blank=True, null=True)),
                ('available_points', models.IntegerField(blank=True, null=True)),
                ('user_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.usersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='UserSurveyOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.TextField(blank=True, null=True)),
                ('offer_link', models.TextField(blank=True, null=True)),
                ('points_for_survey', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_attened', models.BooleanField(blank=True, default=False, null=True)),
                ('attened_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('survey_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.usersurvey')),
            ],
        ),
    ]
