# Generated by Django 3.2.4 on 2023-05-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescreener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_required', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('length_of_interview', models.CharField(blank=True, max_length=100, null=True)),
                ('is_quality_follow_up', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_relevantld_check', models.BooleanField(default=False)),
                ('cpa', models.CharField(blank=True, max_length=100, null=True)),
                ('end_data', models.DateField(blank=True, null=True)),
                ('recruitment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_link', models.URLField(blank=True, null=True)),
                ('surveyTemplate_link', models.URLField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('live_survey_link_for_custom_panel_builidng', models.TextField(blank=True, null=True)),
                ('background_color', models.TextField(blank=True, null=True)),
                ('camapign_image', models.FileField(blank=True, null=True, upload_to='camapainImages/')),
                ('camapign_logo', models.FileField(blank=True, null=True, upload_to='camapainImages/')),
                ('text_color', models.TextField(blank=True, null=True)),
                ('campaign_title', models.TextField(blank=True, null=True)),
                ('p_created_date_time', models.DateTimeField(blank=True, null=True)),
                ('p_updated_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clicks', models.IntegerField(blank=True, null=True)),
                ('total_soi', models.IntegerField(blank=True, null=True)),
                ('total_doi', models.IntegerField(blank=True, null=True)),
                ('total_conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_spent', models.IntegerField(blank=True, null=True)),
                ('total_response_rate', models.FloatField(blank=True, null=True)),
                ('total_completion_rate', models.IntegerField(blank=True, null=True)),
                ('total_invite_sent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelist_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPixcelCodeForCustomPanelBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_code_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('s2s_postback_pixel_code', models.CharField(blank=True, max_length=500, null=True)),
                ('google_pixel_code', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_pixel_code', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeCampaignSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelist_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PixcelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_code_screen', models.CharField(blank=True, max_length=500, null=True)),
                ('s2s_postback_pixel_code', models.CharField(blank=True, max_length=500, null=True)),
                ('google_pixel_code', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_pixel_code', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescreenerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('question_id', models.CharField(blank=True, max_length=100, null=True)),
                ('option_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_supplier_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('supplier_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('panelist_email', models.EmailField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('reply_data', models.TextField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedUserClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clicked', models.BooleanField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign')),
                ('panelist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.usersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('cpa', models.CharField(blank=True, max_length=100, null=True)),
                ('cpi', models.CharField(blank=True, max_length=100, null=True)),
                ('cpc', models.CharField(blank=True, max_length=100, null=True)),
                ('cps', models.CharField(blank=True, max_length=100, null=True)),
                ('cpl', models.CharField(blank=True, max_length=100, null=True)),
                ('compaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='UserClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clicked', models.BooleanField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign')),
                ('panelist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.usersurvey')),
            ],
        ),
    ]
