# Generated by Django 3.2.4 on 2023-05-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescreener', '0001_initial'),
        ('panelengagement', '0001_initial'),
        ('projects', '0001_initial'),
        ('panelbuilding', '0001_initial'),
        ('account', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclicks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='suppliercampaignlink',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='suppliercampaignlink',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supplier'),
        ),
        migrations.AddField(
            model_name='prescreenersurvey',
            name='prescreener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreener.prescreener'),
        ),
        migrations.AddField(
            model_name='pixcelcode',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='pecampaignsurvey',
            name='pecampaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelengagement.pecampaign'),
        ),
        migrations.AddField(
            model_name='generatedpixcelcodeforcustompanelbuilding',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='campaignsurvey',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndashboard',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panelbuilding.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndashboard',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.supplier'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.campaigntype'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='commision_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.commissionmodel'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='account.customuser'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='market_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.country'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='account.customuser'),
        ),
    ]
